# Generated by Django 2.1 on 2018-10-18 10:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_blogmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmodel',
            name='created_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='useryearbook',
            name='dob',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
