# Generated by Django 2.1 on 2018-10-18 10:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20181018_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodel',
            name='created_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='useryearbook',
            name='dob',
            field=models.DateField(),
        ),
    ]
