# Generated by Django 2.1 on 2018-10-19 03:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_auto_20181018_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodel',
            name='created_time',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
