# Generated by Django 2.1 on 2018-10-19 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_blogmodel_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogmodel',
            name='author',
        ),
    ]
